PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX disco:   <http://rdf-vocabulary.ddialliance.org/discovery>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos:	<http://www.w3.org/2004/02/skos/core#>

SELECT ?studyTitle ?studyAbstract ?logicalDataSetTitle
WHERE {
  ?study a disco:Study ;
    dcterms:title ?studyTitle ;
    dcterms:abstract ?studyAbstract ;
    dcterms:subject [ skos:prefLabel "Climate Change" ] ;
    dcterms:temporal [ disco:startDate ?date ] ;
    disco:product ?logicalDataSet .

  ?logicalDataSet a disco:LogicalDataSet ;
    dcterms:title ?logicalDataSetTitle .

  FILTER (?date >= 2000)
}